tests:
  jmeter:
    enabled: false                       # Set to true to enable JMeter test
    JMETER_HOME: '/Users/bharathkumarm/apache-jmeter-5.6.3'     # Set the correct JMeter path
    TEST_PLAN: '/Users/bharathkumarm/Docker/JmeterScript/Wordsmith.jmx'    # JMX file for the test
    REPORT_DIR: '/Users/bharathkumarm/Docker/JmeterScript/jmeter-report'         # Directory for results

  chaos_experiment:
    enabled: true                       # Set to true to enable chaos experiment
    TARGET_IDENTIFIER: '192.168.65.3' # Host to target
    CPU_LENGTH: 30                      # Duration of CPU attack
    CPU_CORE: 1                         # Number of cores to impact
    CPU_CAPACITY: 100                   # Percentage of total CPU capacity to consume

project:
  github_repo: 'https://github.com/bharathbk07/wordsmith.git'  # Placeholder for GitHub repository name
  branch_name: 'main'         # Placeholder for branch name